/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lpr_LPR */

#ifndef _Included_com_lpr_LPR
#define _Included_com_lpr_LPR
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lpr_LPR
 * Method:    DetectLPR
 * Signature: ([SIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_lpr_LPR_DetectLPR
  (JNIEnv *, jobject, jshortArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
